Updated install & uninstall scripts

diff --git a/package-scripts/occi-server/makeselfinst b/package-scripts/occi-server/makeselfinst
--- a/package-scripts/occi-server/makeselfinst
+++ b/package-scripts/occi-server/makeselfinst
@@ -7,6 +7,7 @@ PROGNAME=`basename $0`
 INSTALLER_DIR=`dirname $0`
 DEST_DIR=/opt/occi-server
 CONFIG_DIR=/etc/occi-server
+LOG_DIR=/var/log/occi-server
 USAGE="usage: $0"
 
 error_exit()
@@ -16,9 +17,26 @@ error_exit()
 }
 
 # move the actual files into place
-rm -rf $DEST_DIR/* || error_exit "Cannot remove contents of $DEST_DIR"
-mkdir -p $DEST_DIR || error_exit "Cannot create $DEST_DIR"
-cp -R $INSTALLER_DIR $DEST_DIR || error_exit "Cannot install to $DEST_DIR"
+rm -rf $DEST_DIR/* || error_exit "Could not remove contents of $DEST_DIR"
+mkdir -p $DEST_DIR || error_exit "Could not create $DEST_DIR"
+cp -R $INSTALLER_DIR $DEST_DIR || error_exit "Could not install to $DEST_DIR"
 rm -f $DEST_DIR/$PROGNAME
+
+# chown
+chown -R root:root $DEST_DIR || error_exit "Could not chown $DEST_DIR to root:root"
+
+# prepare dir structure
+mkdir -p $CONFIG_DIR || error_exit "Could not create $CONFIG_DIR"
+mkdir -p $LOG_DIR || error_exit "Could not create $LOG_DIR"
+
+# create the rocci user
+id -u rocci
+if [ "$?" -ne "0" ]; then
+  useradd --system --shell /bin/false rocci || error_exit "Could not create the rocci user account"
+  usermod -L rocci || error_exit "Could not lock the rocci user account"
+fi
+
+# chown log dir
+chown -R rocci:rocci $LOG_DIR || error_exit "Could not chown $LOG_DIR to rocci:rocci"
 
 exit 0
diff --git a/package-scripts/occi-server/postinst b/package-scripts/occi-server/postinst
--- a/package-scripts/occi-server/postinst
+++ b/package-scripts/occi-server/postinst
@@ -4,13 +4,35 @@
 # after package is installed.
 #
 
-PROGNAME=$(basename $0)
+PROGNAME=`basename $0`
+INSTALLER_DIR=`dirname $0`
+DEST_DIR=/opt/occi-server
+CONFIG_DIR=/etc/occi-server
+LOG_DIR=/var/log/occi-server
+USAGE="usage: $0"
 
-function error_exit
+error_exit()
 {
   echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
   exit 1
 }
+
+# chown
+chown -R root:root $DEST_DIR || error_exit "Could not chown $DEST_DIR to root:root"
+
+# prepare dir structure
+mkdir -p $CONFIG_DIR || error_exit "Could not create $CONFIG_DIR"
+mkdir -p $LOG_DIR || error_exit "Could not create $LOG_DIR"
+
+# create the rocci user
+id -u rocci
+if [ "$?" -ne "0" ]; then
+  useradd --system --shell /bin/false rocci || error_exit "Could not create the rocci user account"
+  usermod -L rocci || error_exit "Could not lock the rocci user account"
+fi
+
+# chown log dir
+chown -R rocci:rocci $LOG_DIR || error_exit "Could not chown $LOG_DIR to rocci:rocci"
 
 echo "Thank you for installing occi-server!"
 
diff --git a/package-scripts/occi-server/postrm b/package-scripts/occi-server/postrm
--- a/package-scripts/occi-server/postrm
+++ b/package-scripts/occi-server/postrm
@@ -4,6 +4,27 @@
 # after package is uninstalled.
 #
 
-echo "Occi-server has been uninstalled!"
+PROGNAME=`basename $0`
+INSTALLER_DIR=`dirname $0`
+DEST_DIR=/opt/occi-server
+CONFIG_DIR=/etc/occi-server
+LOG_DIR=/var/log/occi-server
+USAGE="usage: $0"
+
+error_exit()
+{
+  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
+  exit 1
+}
+
+if [ -d "$CONFIG_DIR" ]; then
+  rm -rf $CONFIG_DIR
+fi
+
+if [ -d "$LOG_DIR" ]; then
+  rm -rf $LOG_DIR
+fi
+
+echo "occi-server has been uninstalled!"
 
 exit 0
