Updated post* scripts to support rOCCI-server v2

diff --git a/package-scripts/occi-server/postrm b/package-scripts/occi-server/postrm
--- a/package-scripts/occi-server/postrm
+++ b/package-scripts/occi-server/postrm
@@ -6,11 +6,12 @@
 
 PROGNAME=`basename $0`
 INSTALLER_DIR=`dirname $0`
-DEST_DIR=/opt/occi-server
-LINK_CONFIG_DIR=/etc/occi-server
-LINK_DEST_DIR=/opt/rOCCI-server
-LINK_LOG_DIR=/var/log/occi-server
 USAGE="usage: $0"
+
+DEST_DIR="/opt/occi-server"
+CONFIG_DIR="/etc/occi-server"
+CONFIG_FILE="${CONFIG_DIR}/rocci_server.yml"
+LOG_DIR="/var/log/occi-server"
 
 error_exit()
 {
@@ -18,37 +19,18 @@ error_exit()
   exit 1
 }
 
-if [ "X$1" = "Xupgrade" ] || [ "X$1" = "X1" ]; then
-  echo "Skipping clean-up, this is an upgrade!"
-  exit 0
-fi
-
-if [ -L "$LINK_CONFIG_DIR" ]; then
-  rm $LINK_CONFIG_DIR || error_exit "Could not unlink $LINK_CONFIG_DIR"
-fi
-
-if [ -L "$LINK_LOG_DIR" ]; then
- rm $LINK_LOG_DIR || error_exit "Could not unlink $LINK_LOG_DIR"
-fi
-
-if [ -L "$LINK_DEST_DIR" ]; then
-  rm $LINK_DEST_DIR || error_exit "Could not unlink $LINK_DEST_DIR"
-fi
-
-if [ -d "$DEST_DIR" ]; then
-  ls $DEST_DIR/embedded/app/rOCCI-server/log/*.log > /dev/null 2>&1
-
-  if [ "$?" -eq "0" ]; then
-    mkdir -p $LINK_LOG_DIR || error_exit "Could not create a backup directory $LINK_LOG_DIR"
-    cp -p $DEST_DIR/embedded/app/rOCCI-server/log/*.log $LINK_LOG_DIR || error_exit "Could not backup log files to $LINK_LOG_DIR"
+if [ "X$1" = "purge" ] || [ "X$1" = "X0" ]; then
+  if [ -d "$CONFIG_DIR" ]; then
+    rm -rf "$CONFIG_DIR" || error_exit "Could not unlink $CONFIG_DIR"
   fi
-fi
 
-if [ -f "/etc/redhat-release" ]; then
-  rm -rf $DEST_DIR || error_exit "Could not unlink $DEST_DIR"
-else
-  rmdir $DEST_DIR/runtime > /dev/null 2>&1 || /bin/true
-  rmdir $DEST_DIR > /dev/null 2>&1 || /bin/true
+  if [ -d "$LOG_DIR" ]; then
+    rm -rf "$LOG_DIR" || error_exit "Could not unlink $LOG_DIR"
+  fi
+
+  if [ -d "$DEST_DIR" ]; then
+    rm -rf "$DEST_DIR" || error_exit "Could not unlink $DEST_DIR"
+  fi
 fi
 
 echo "occi-server has been uninstalled!"
